 [2024-05-05 10:44:31,001: INFO: main: Welocome]
[2024-05-05 10:44:31,001: INFO: main: >>>>>>>>stage Data Ingestion stage started<<<<<<<<<<<<<]
[2024-05-05 10:44:31,005: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-05 10:44:31,006: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-05 10:44:31,007: INFO: common: created directory at: artifacts]
[2024-05-05 10:44:31,485: ERROR: main: HTTP Error 404: Not Found]
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    data_ingestion.main()
  File "d:\nlp\end to end text summarizer\src\textsummarizer\pipeline\stage_01_data_ingestion.py", line 18, in main
    raise e
  File "d:\nlp\end to end text summarizer\src\textsummarizer\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "d:\nlp\end to end text summarizer\src\textsummarizer\components\data_ingestion.py", line 14, in download_file
    filename,headers=request.urlretrieve(
  File "C:\Users\shree\miniconda3\envs\textS\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\shree\miniconda3\envs\textS\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\shree\miniconda3\envs\textS\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\shree\miniconda3\envs\textS\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\Users\shree\miniconda3\envs\textS\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\shree\miniconda3\envs\textS\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\shree\miniconda3\envs\textS\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[2024-05-05 10:45:54,882: INFO: main: Welocome]
[2024-05-05 10:45:54,883: INFO: main: >>>>>>>>stage Data Ingestion stage started<<<<<<<<<<<<<]
[2024-05-05 10:45:54,886: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-05 10:45:54,887: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-05 10:45:54,888: INFO: common: created directory at: artifacts]
[2024-05-05 10:45:55,324: ERROR: main: HTTP Error 404: Not Found]
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    data_ingestion.main()
  File "d:\nlp\end to end text summarizer\src\textsummarizer\pipeline\stage_01_data_ingestion.py", line 18, in main
    raise e
  File "d:\nlp\end to end text summarizer\src\textsummarizer\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "d:\nlp\end to end text summarizer\src\textsummarizer\components\data_ingestion.py", line 14, in download_file
    filename,headers=request.urlretrieve(
  File "C:\Users\shree\miniconda3\envs\textS\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\shree\miniconda3\envs\textS\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\shree\miniconda3\envs\textS\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\shree\miniconda3\envs\textS\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\Users\shree\miniconda3\envs\textS\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\shree\miniconda3\envs\textS\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\shree\miniconda3\envs\textS\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[2024-05-05 10:49:43,471: INFO: main: Welocome]
[2024-05-05 10:49:43,471: INFO: main: >>>>>>>>stage Data Ingestion stage started<<<<<<<<<<<<<]
[2024-05-05 10:49:43,485: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-05 10:49:43,486: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-05 10:49:43,487: INFO: common: created directory at: artifacts]
[2024-05-05 10:49:44,736: ERROR: main: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip']
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    data_ingestion.main()
  File "d:\nlp\end to end text summarizer\src\textsummarizer\pipeline\stage_01_data_ingestion.py", line 18, in main
    raise e
  File "d:\nlp\end to end text summarizer\src\textsummarizer\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "d:\nlp\end to end text summarizer\src\textsummarizer\components\data_ingestion.py", line 14, in download_file
    filename,headers=request.urlretrieve(
  File "C:\Users\shree\miniconda3\envs\textS\lib\urllib\request.py", line 257, in urlretrieve
    tfp = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip'
[2024-05-05 10:50:31,486: INFO: main: Welocome]
[2024-05-05 10:50:31,486: INFO: main: >>>>>>>>stage Data Ingestion stage started<<<<<<<<<<<<<]
[2024-05-05 10:50:31,490: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-05 10:50:31,491: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-05 10:50:31,492: INFO: common: created directory at: artifacts]
[2024-05-05 10:50:34,096: INFO: data_ingestion: artifacts/data_ingestion/data.zipdownlad! with following info:
Connection: close
Content-Length: 7903594
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "dbc016a060da18070593b83afff580c9b300f0b6ea4147a7988433e04df246ca"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 4F02:CA2B2:1699F1:1EC62B:663716EB
Accept-Ranges: bytes
Date: Sun, 05 May 2024 05:20:27 GMT
Via: 1.1 varnish
X-Served-By: cache-maa10239-MAA
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1714886427.471341,VS0,VE1
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 46a5529daf53a820e89130cd628d42aa9d06fcc9
Expires: Sun, 05 May 2024 05:25:27 GMT
Source-Age: 47

]
[2024-05-05 10:50:34,242: INFO: main: >>>>>>>>stage Data Ingestion stagecompleted<<<<<<<<<<<<<]
[2024-05-05 10:50:34,243: INFO: main: Welocome]
[2024-05-05 10:50:34,243: INFO: main: >>>>>>>>stage Data Validation stage started<<<<<<<<<<<<<]
[2024-05-05 10:50:34,246: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-05 10:50:34,247: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-05 10:50:34,248: INFO: common: created directory at: artifacts]
[2024-05-05 10:50:34,249: INFO: common: created directory at: artifacts/data_validation]
[2024-05-05 10:50:34,250: INFO: main: >>>>>>>>stage Data Validation stagecompleted<<<<<<<<<<<<<]
